/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package hmapp.hm.com.hmandroidapp.util;


public class MathUtil {
    
    public static boolean isInt(String value) {


        return  true;
    }

}
