/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package hmapp.hm.com.hmandroidapp.util;

import android.content.Context;
import android.app.AlertDialog;
import android.content.DialogInterface;
import android.app.Activity;

public class windowsUtil {
    
    public static void alertInfo_ok(String info, Context content) {
        AlertDialog.Builder builder = new AlertDialog.Builder(content);
        builder.setMessage(info).setPositiveButton("\u786e\u5b9a", new DialogInterface.OnClickListener() {
            public void onClick(DialogInterface dialog, int id) {
            }
        });
        AlertDialog alert = builder.create();
        alert.show();
    }

}
